site_name: Pirate Weather
site_url: https://pirateweather.net
repo_url: https://github.com/Pirate-Weather/pirateweather
repo_name: 'GitHub'
theme: 
  name: 'material' 
  favicon: images/pw_favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'deep orange'
      accent: 'deep orange'
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'deep orange'
      toggle:
        icon: lucide/moon
        name: Switch to light mode
  features:
    - navigation.expand
    
nav:
  - Introduction: 'index.md'
  - 'API': 'API.md'
  - 'OpenAPI Specification': 'Specification.md'
  - 'Home Assistant': 'ha.md'
  - 'Data Sources' : 'DataSources.md'
  - 'Changelog': 'changelog.md'
  - 'Roadmap': 'https://github.com/Pirate-Weather/pirateweather/discussions/414'
  - 'Issue Tracker': 'https://github.com/Pirate-Weather/pirateweather/issues'
  - 'Terms of Service' : 'https://pirate-weather.apiable.io/terms'
  - Blog:
    - 'Indident Reports': 'Blog/IncidentReports.md'  
    - 'CloudWatch Insights': 'Blog/CloudWatchInsights.md'
    - 'Kong Gateway': 'Blog/KongGatewayInfrastructure.md'
    - 'Infrastructure Overview': 'Blog/InfrastructureOverview.md'
    - 'Previous Versions- v0.1': 'Blog/indexv01.md'
    
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
   
extra_css:
  - stylesheets/extra.css
